/**
 * Chrome/Edge exported bookmarks use Netscape Bookmark File format.
 * We'll parse all <a href="...">Title</a> into flat links (folders ignored).
 */

function safeText(s) {
  return (s ?? "").toString();
}

function normalizeUrl(input) {
  const raw = safeText(input).trim();
  if (!raw) return null;
  try {
    const u = new URL(raw);
    if (u.protocol !== "http:" && u.protocol !== "https:") return null;
    return u.toString();
  } catch {
    return null;
  }
}

function escapeHtml(s) {
  return safeText(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/**
 * @param {string} html
 * @returns {Array<{alias: string, url: string}>}
 */
export function parseBookmarksHtml(html) {
  const doc = new DOMParser().parseFromString(html, "text/html");
  const links = [];
  const seen = new Set();
  for (const a of doc.querySelectorAll("a[href]")) {
    const url = normalizeUrl(a.getAttribute("href"));
    if (!url) continue;
    if (seen.has(url)) continue;
    seen.add(url);
    const alias = safeText(a.textContent).trim() || url;
    links.push({ alias, url });
  }
  return links;
}

/**
 * @param {Array<{alias: string, url: string}>} items
 * @returns {string} HTML content
 */
export function makeBookmarksHtml(items) {
  const now = new Date().toISOString();
  const lines = [];
  lines.push("<!DOCTYPE NETSCAPE-Bookmark-file-1>");
  lines.push("<!-- This is an automatically generated file.");
  lines.push("     It will be read and overwritten.");
  lines.push(`     Generated by StartLink at ${escapeHtml(now)} -->`);
  lines.push('<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">');
  lines.push("<TITLE>Bookmarks</TITLE>");
  lines.push("<H1>Bookmarks</H1>");
  lines.push("<DL><p>");
  lines.push(`  <DT><H3 ADD_DATE="${Date.now()}">StartLink</H3>`);
  lines.push("  <DL><p>");
  for (const it of items || []) {
    const url = normalizeUrl(it.url);
    if (!url) continue;
    const alias = (safeText(it.alias).trim() || url).slice(0, 200);
    lines.push(`    <DT><A HREF="${escapeHtml(url)}">${escapeHtml(alias)}</A>`);
  }
  lines.push("  </DL><p>");
  lines.push("</DL><p>");
  return lines.join("\n");
}





